version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: f2f-db
    restart: always
    environment:
      POSTGRES_USER: f2fadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./dump_sql_new.sql:/docker-entrypoint-initdb.d/dump_sql_new.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: f2f-db-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    image: food2food:latest
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/database
      SPRING_DATASOURCE_USERNAME: f2fadmin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres