version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: f2f-db
    restart: always
    environment:
      POSTGRES_USER: f2fadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./init_dump.sql:/docker-entrypoint-initdb.d/init_dump.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: f2f-db-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres